/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.appliancesinfo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import java.util.regex.*; 
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author aryan
 */
public class AppliancesInfo extends javax.swing.JFrame {
 
    private ArrayList<TableObject> data = new ArrayList();
    
    private String Range;

    /**
     * Creates new form AppliancesInfo
     */
    public AppliancesInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtModPrice = new javax.swing.JTextField();
        lowrangeBtn = new javax.swing.JRadioButton();
        midrangeBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModDiscount = new javax.swing.JTextField();
        txtModName = new javax.swing.JTextField();
        txtModNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        cboxMod = new javax.swing.JComboBox<>();
        clearBtn = new javax.swing.JButton();
        highrangeBtn = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        price = new javax.swing.JTextField();
        cboxsMod = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sortBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matrix Mobile Accessories ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "Input Mobile Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        txtModPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModPriceActionPerformed(evt);
            }
        });
        txtModPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModPriceKeyTyped(evt);
            }
        });

        buttonGroup1.add(lowrangeBtn);
        lowrangeBtn.setText("Low ");
        lowrangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowrangeBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(midrangeBtn);
        midrangeBtn.setText("Mid");
        midrangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midrangeBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Range :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Model Name :");

        delBtn.setBackground(new java.awt.Color(255, 255, 255));
        delBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delBtn.setForeground(new java.awt.Color(204, 0, 204));
        delBtn.setText("DELETE");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Model Number :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Category :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Discount :");

        txtModDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModDiscountActionPerformed(evt);
            }
        });

        txtModName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModNameActionPerformed(evt);
            }
        });

        txtModNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModNumberActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Price :");

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 204, 204));
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cboxMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Budget", "Normal", "Gaming", "Flagship", "Premium", "Folding" }));
        cboxMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxModActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 255, 255));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(51, 255, 51));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(highrangeBtn);
        highrangeBtn.setText("High");
        highrangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highrangeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(addBtn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lowrangeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(midrangeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(highrangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtModName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtModNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtModPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delBtn)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lowrangeBtn)
                        .addComponent(midrangeBtn)
                        .addComponent(highrangeBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtModPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtModDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(delBtn)
                    .addComponent(clearBtn))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Mobile Details Table", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        modTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Model Number", "Model Name", "Category", "Range", "Price", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        modTable.setToolTipText("");
        jScrollPane1.setViewportView(modTable);
        if (modTable.getColumnModel().getColumnCount() > 0) {
            modTable.getColumnModel().getColumn(0).setResizable(false);
            modTable.getColumnModel().getColumn(1).setResizable(false);
            modTable.getColumnModel().getColumn(2).setResizable(false);
            modTable.getColumnModel().getColumn(3).setResizable(false);
            modTable.getColumnModel().getColumn(4).setResizable(false);
            modTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        cboxsMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Budget", "Normal", "Gaming", "Flagship", "Premium", "Folding" }));
        cboxsMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxsModActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(0, 153, 0));
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Model Price :");

        jLabel8.setText("Category :");

        sortBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sortBtn.setForeground(new java.awt.Color(255, 102, 0));
        sortBtn.setText("SORT");
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxsMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sortBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboxsMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(sortBtn))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        openMenu.setText("Open");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuActionPerformed(evt);
            }
        });
        jMenu1.add(openMenu);

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModNameActionPerformed

    private void txtModPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModPriceActionPerformed

    private void txtModDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModDiscountActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        /**
         * This method is called when the add button is clicked.
         * This method has certain validation standards which should be maintained before entering the values to the table.
         */
        String modNumber = txtModNumber.getText();
        String modName = txtModName.getText();
        String modPrice = txtModPrice.getText();
        String modDiscount = txtModDiscount.getText();
        String modCategory = cboxMod.getSelectedItem().toString();
           
        
        if(!modNumber.equals("") && !modName.equals("") && !modPrice.equals("") && !modDiscount.equals("")){
            if(Pattern.compile("A[0-9]{2}B[0-9]{2}").matcher(modNumber).matches()){
            if(buttonGroup1.getSelection()!=null){
             
            int rowCount = modTable.getRowCount();        
            boolean emptyRowFlag = false;
            int nextRow=0;
            String s ;
            do{
                s = (String)modTable.getValueAt(nextRow,0);
                if(s!=null && s.length()!=0){
                    nextRow++;
                }else{
                emptyRowFlag=true;
            }
            }
            while(nextRow<rowCount && !emptyRowFlag);
            if(emptyRowFlag){
                String[] value={modNumber,modName,modCategory,Range,modPrice,modDiscount};
                int colCount = modTable.getColumnCount();
                for(int i=0;i<colCount;i++){
                    modTable.setValueAt(value[i], nextRow, i);

                }
           
            }else{
                    JOptionPane.showMessageDialog(rootPane,"No Empty Rows Found","Error",0);
                }
                TableObject a = new TableObject(modNumber,modName,modCategory,Range,modPrice,modDiscount);
                    data.add(a);
            } else{
                    JOptionPane.showMessageDialog(rootPane,"Select Range","Error",1);
                    }
                }else{
                        JOptionPane.showMessageDialog(rootPane,"Write Correct Model Number","Error",1);
                    }
        }else{
              JOptionPane.showMessageDialog(rootPane,"Fill all the Fields","Error",1);
            }          
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
         /* This method is called when the delete button is clicked.
         * This method deletes the value of the specific row in the given table.
         */
        DefaultTableModel delmodel = (DefaultTableModel) modTable.getModel();
        try{
            int SelectedRowIndex = modTable.getSelectedRow();
            delmodel.removeRow(SelectedRowIndex);
        }catch(Exception ed){
            JOptionPane.showMessageDialog(rootPane,"Please Select a Row to delete","Error",1);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void txtModNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModNumberActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
         /* This method is called when the clear button is clicked.
         * This method has clears the given data from the input section.
         */
        txtModNumber.setText("");
        txtModName.setText("");
        txtModPrice.setText("");
        txtModDiscount.setText("");
        cboxMod.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void cboxModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxModActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboxModActionPerformed

    private void lowrangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowrangeBtnActionPerformed
        // TODO add your handling code here:
        Range = "Low";
    }//GEN-LAST:event_lowrangeBtnActionPerformed

    private void midrangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midrangeBtnActionPerformed
        // TODO add your handling code here:
        Range = "Mid";
        
    }//GEN-LAST:event_midrangeBtnActionPerformed

    private void highrangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highrangeBtnActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_highrangeBtnActionPerformed

    private void txtModPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModPriceKeyTyped
        // TODO add your handling code here:
        char numb = evt.getKeyChar(); 
        if (!(numb >= '0' && numb <= '9')){
            evt.consume();
        } 
    }//GEN-LAST:event_txtModPriceKeyTyped

    private void cboxsModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxsModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxsModActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
         /* This method is called when the search button is clicked.
         * This method sorts and searches the given data.
         */
        String Mprice = price.getText();
       try{
           sort(data);
       
        int index = BinarySearch(data,0,data.size()-1,Integer.parseInt(Mprice));
        if(index==-1){
            JOptionPane.showMessageDialog(rootPane,"Accessory not found","Error",0);
        }else{
            JOptionPane.showMessageDialog(rootPane,"The Model Number is"+ data.get(index).getModNumber()+",\n"+
                   "The Model Name is"+ data.get(index).getModName()+",\n"+
                    "The Model Category is"+ data.get(index).getModCategory() +",\n"+
                    "The Model Range is"+ data.get(index).getRange() +",\n"+
                    
                    "The Model Discount is"+ data.get(index).getModDiscount() +",\n","InformationMessage",1);
        }
    }catch(NumberFormatException exe){
        JOptionPane.showMessageDialog(rootPane,"The system doesn't contain the given data" ,"Error",0);
    }
    }//GEN-LAST:event_searchBtnActionPerformed
    private int BinarySearch(ArrayList<TableObject> data, int low, int high, int value){
        if(low<=high){
            int mid = (high + low)/2;
             if(data.get(mid).getModPrice()== value){
             return mid;
            }
            else if(data.get(mid).getModPrice()< value){
            return BinarySearch(data, mid+1, high, value);
            }else{
            return BinarySearch(data,low, mid-1, value);
            }
         }else{
            return -1;
         }

    }
    private void openMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuActionPerformed
        // TODO add your handling code here:
         /* This method is called when the open button is clicked.
         * This method has opens the data.
         */
        try {
            DefaultTableModel model = (DefaultTableModel)modTable.getModel();
            model.setRowCount(0);
            model.setRowCount(17);
            BufferedReader br = new BufferedReader(new FileReader("data.csv"));
            String row = "";
           while((row=br.readLine())!=null){
                String[]value = row.split(",");
                model.addRow(value);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane,"File not found","Error",2);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane,"IOException","Error",2);
        }   
    }//GEN-LAST:event_openMenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
         /* This method is called when the exit button is clicked.
         * This method has closes the program.
         */
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        // TODO add your handling code here:
         /* This method is called when the sort button is clicked.
         * This method sorts the given data according to price.
         */
          for(int i = 0;i<data.size()-1;i++){
            int minPos = i;
            for(int j = i+1;j<data.size();j++){
                if(data.get(minPos).getModPrice()>data.get(j).getModPrice()){
                    minPos = j;
                }
            }
            Collections.swap(data,minPos,i);
        }
        loadTable();
        LoadToCSV();  
    }//GEN-LAST:event_sortBtnActionPerformed
public void loadTable(){
    DefaultTableModel model = (DefaultTableModel)modTable.getModel();
    model.setRowCount(0);
    
    for(TableObject s: data){
        String value []= {s.getModNumber(),s.getModName(),s.getModCategory(),s.getRange(),Long.toString(s.getModPrice()),s.getModDiscount()};
        model.addRow(value);
    }
}

public void LoadToCSV(){
    try{
    File file = new File("data.csv");
    if(!file.isFile()){
        file.createNewFile();
        
    }
    FileWriter wr = new FileWriter(file);
    for(TableObject s: data){
        String [] value = {s.getModNumber(),s.getModName(),s.getModCategory(),s.getRange(),Long.toString(s.getModPrice()),s.getModDiscount()};
  
        for(int i = 0; i<value.length;i++){
            wr.append(value[i]);
            if(i ==value.length-1){
                break;
            }
            wr.append(",");
        }
        wr.append("\n");
    }
    wr.flush();
    wr.close();
}catch(IOException exe){
    JOptionPane.showMessageDialog(rootPane, "File not found ","Error",0);
}
}

public void sort (ArrayList<TableObject>data){ 
    /* 
     * This method sorts the given data using arrays.
    */
    for (int i = 0; i < data.size() -1; i++){
        int minpos = i;
        for( int j = i+1; j < data.size(); j++){
            if(data.get(minpos).getModPrice()>data.get(j).getModPrice()){
                    minpos = j;
                
            }
        }
            Collections.swap(data,minpos,i);
    }
}   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppliancesInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboxMod;
    private javax.swing.JComboBox<String> cboxsMod;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JRadioButton highrangeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lowrangeBtn;
    private javax.swing.JRadioButton midrangeBtn;
    private javax.swing.JTable modTable;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JTextField price;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton sortBtn;
    private javax.swing.JTextField txtModDiscount;
    private javax.swing.JTextField txtModName;
    private javax.swing.JTextField txtModNumber;
    private javax.swing.JTextField txtModPrice;
    // End of variables declaration//GEN-END:variables
}
